accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('', views.index, name='index'),
    path('<int:user_pk>/',views.detail, name='detail'),
    path('update/',views.update, name='update'),
    path('logout/', views.logout, name='logout'),
    path('password/', views.change_password, name='change_password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = 'reviews'


urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path("<int:review_pk>/delete/", views.delete, name="delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

reviews/models.py
from django.db import models

# Create your models here.
class Reviews(models.Model):
    # 리뷰제목
    title = models.CharField(max_length=30)
    content = models.TextField()
    # 영화 이름
    movie_name = models.CharField(max_length=30)
    grade = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', )

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('last_name', 'first_name', 'email')

reviews/forms.py
from django import forms
from .models import Reviews

class ReviewsForm(forms.ModelForm):

    class Meta:
        model = Reviews
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
# 로그인 입력용 / 비밀번호 변경용 form
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
# 로그인 기능
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth import get_user_model

# 비밀번호 변경하고 난 뒤 세션 무효화 방지용
from django.contrib.auth import update_session_auth_hash

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        # AuthenticationFrom은 ModelForm이 아님
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 form에서 인증된 유저 정보를 가져옴
            auth_login(request, form.get_user())
            ######## 다른 곳으로 보내줄 곳을 위해 수정할 것! #######
            return redirect('accounts:index')

    else:
         form = AuthenticationForm()
    context = {
        'form' : form
    }
    ######## 다른 곳으로 보내줄 곳을 위해 수정할 것! #######
    return render(request, 'accounts/login.html', context)

def index(request):
    user = get_user_model().objects.all()
    context = {
        'user_': user
    }
    return render(request, "accounts/index.html", context)

def detail(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    context ={
        'user_' : user
    }
    return render(request,"accounts/detail.html",context)

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        # form = CustomUserChangeForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
    'form': form,
    }
    return render(request, 'accounts/update.html', context)


def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
        return redirect('accounts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

reviews/views.py
from django.shortcuts import render, redirect
from .models import Reviews
from .forms import ReviewsForm


def index(request):
    reviews = Reviews.objects.all()
    context = {
        'reviews': reviews
    }
    return render(request, 'reviews/index.html', context)


# Create your views here.
def create(request):
    if request.method == 'POST':
        # DB에 저장하는 로직
        review_form = ReviewsForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect('reviews:index')
    else: 
        review_form = ReviewsForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'reviews/create.html', context=context)

def detail(request,review_pk):
    reviews = Reviews.objects.get(pk=review_pk)
    context = {
        'reviews':reviews
    }
    return render(request, 'reviews/detail.html', context)


def update(request, review_pk):
    reviews = Reviews.objects.get(pk=review_pk)
    
    if request.method == 'POST':
        review_form = ReviewsForm(request.POST, instance=reviews)
        
        if review_form.is_valid():
            review_form.save()
            return redirect("reviews:detail", reviews.pk)

    else:
        review_form = ReviewsForm(instance=reviews)

    context = {
        "review_form": review_form,
    }

    return render(request, 'reviews/create.html', context)

def delete(request, review_pk):
    reviews = Reviews.objects.get(pk=review_pk)
    reviews.delete()
    return redirect("reviews:index")

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1> 비밀번호 변경 </h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="제출" %}
 
 </form>

{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block body %}
  <h1>회원 정보 조회</h1>
  {{ user_.pk }}번<br>
  {{ user_.username }}님<br>
  {{ user_.last_name }}
  {{ user_.first_name }}<br>
  {{ user_.email }}

  <a href="{% url 'accounts:update'%}" type="button" class="btn btn-outline-info">
    수정
  </a>

{% endblock body %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block body %}

  <table class="table table-dark table-striped">
    <thead>
      <tr>
        <th scope="col">pk</th>
        <th scope="col">Username</th>
        <th scope="col">e-mail</th>
      </tr>
    </thead>

    {% for i in user_ %}
      <tbody>
        <tr>
          <td>
            {{ i.pk }}
          </td>
          <td>
            <a href="{% url 'accounts:detail' i.pk %}">
              {{ i.username}}
            </a>
          </td>
          <td>
            {{ i.email}}
          </td>
        {% endfor %}
      </tr>
    </tbody>
  </table>

  <a href="" type="button" class="btn btn-outline-info">
    Home
  </a>

  <a href="" type="button" class="btn btn-outline-info">
    회원가입
  </a>


  
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>로그인</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit">제출</button>
  </form>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit">제출</button>

  </form>
{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<h1> 프로필 업데이트 </h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="제출" %}
 </form>

{% endblock %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% block body %}
  {% load django_bootstrap5 %}

  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <h1> 생성 화면 </h1>
  <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form review_form %}

    {% bootstrap_button "저장" button_type="submit" button_class="btn-primary" %}
  </form>
  {% endblock%}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% block body %}

  <h1>영화 리뷰 정보</h1>
  <p>{{ reviews.movie_name }}
    |
    {{ reviews.title }}</p>

  <p>영화 내용:{{ reviews.content }}</p>
  <p>영화 등급:{{ reviews.grade }}</p>
  {{ reviews.created_at }}
  {{ reviews.updated_at }}

  <a href="{% url 'reviews:update' reviews.pk %}">수정</a>
  <a href="{% url 'reviews:delete' reviews.pk %}">삭제</a>

{% endblock body %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% block body %}

  <h1>
    인덱스 페이지
  </h1>

  {% for review in reviews %}

    <p>{{ review.movie_name }}
      |
      <a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
    </p>

  {% endfor %}

  {% endblock%}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% block body %}
  {% load django_bootstrap5 %}

  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <h1> 수정 </h1>
  <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form review_form %}

    {% bootstrap_button "수정" button_type="submit" button_class="btn-primary" %}
  </form>
  {% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <div class="d-flex">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'reviews:index' %}">리뷰목록</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'reviews:create' %}">리뷰작성</a>
              </li>
            </ul>
          </div>
        </div>
        <div>
          {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:detail' user.pk %}">{{ request.user }}</a>
            <a href="{% url 'accounts:logout' %}" type="button" class="btn btn-outline-info">
              로그아웃
            </a>
          {% else %}
            <a href="{% url 'accounts:signup' %}" type="button" class="btn btn-outline-info">
              회원가입
            </a>
            <a href="{% url 'accounts:login' %}" type="button" class="btn btn-outline-info">
              로그인
            </a>
          {% endif %}
        </div>
      </div>
    </nav>

    <h2>made by KO, JS, SH</h2>

    {% block body %}{% endblock body %}

  </body>

</html>